name: FroggyXChat
version: 1.0.0
main: com.froggy.chat.FroggyXChat
api-version: '1.20'
description: A chat formatting plugin for the FroggySMP
author: Froggy
depend: [LuckPerms]
softdepend: [PlaceholderAPI]
commands:
  froggychat:
    description: FroggyXChat core commands.
    usage: "Usage: /froggychat <reload>"
permissions:
  froggychat.reload:
    description: Allows use of /froggychat reload
    default: op
